### PR TITLE
Various additions and updates to the main list

### PR DESCRIPTION
**Pull request by abcasada**
Added two relevant tools. Copied the description of each one from the beginning of its Readme.

### CODE REVIEW

**Comment by Shakil-Shahadat** [comment]
Thanks for the 'Overseerr' link but I can't accept the other because of its nature. Please remove the other.

**Comment by abcasada** [comment]
I have removed it, and also suggested removing another for the same reason.

**Comment by abcasada** [comment]
FYI: I have found several more relevant tools, so will be adding another commit to this PR soon.

**Comment by abcasada** [comment]
This is nearly all the changes I have in mind for now, except one other tool I heard about:

- [Flaresolverr](https://github.com/FlareSolverr/FlareSolverr) FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD protection.

I am not entirely sure the use case for this or the appropriate section. What do you think @Shakil-Shahadat?

**Comment by Shakil-Shahadat** [comment]
Thank you so much for all these changes.

I hate Cloudflare checks but how do I run FlareSolverr? Running an entire software to bypass occasional checks sounds too much. I must be missing something.

**Comment by abcasada** [comment]
> Thank you so much for all these changes.
> 
> I hate Cloudflare checks but how do I run FlareSolverr? Running an entire software to bypass occasional checks sounds too much. I must be missing something.

You're welcome. Glad to help.

After more looking I found a primary use for it.

https://wiki.servarr.com/en/prowlarr/settings#flaresolverr-proxy-settings

Without it there are a lot of indexers that can't be searched by Prowlarr. I'll add a PR for it now that I understand it.

**Comment by Shakil-Shahadat** [comment]
Thanks again.

**Pull request merged**
