### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by KonoromiHimaries**
- Replace Decentraleyes to LocalCDN
- Add Save to the Wayback Machine
- Add LibRedirect
- Removed TamperMonkey because is duplicated with Violentmonkey
- Add Stylus
- Add User Agent Switcher and Manager
- Add Search by Image
- Add ClearURLs
- Add Canvas Blocker
- Add SimpleWall
- Removed YouTube Vanced because is duplicated with ReVanced
- Replace Tachiyomi to TachiyomiJ2K
- Add Mangal
- Add Library Genesis IPFS
- Add Stream Recorder
- Add The Stream Detector
- Add Lux
- Add Streamlink
- Add section Encryption
- Add animdl
- Add ani-cli
- Add section Novels
- Add SimpleDnsCrypt
- Add Privacy Guides
- Removed 4anime + Anime8 + Kissanime + Anime Twist
- Add Dodi Repacks
- Add Manga Reader
- Add Zoro
- Add anihdplay
- Add Manganelo
- Add Anime X Stream
- Add Stubby
- Add dnscrypt-proxy 2
- Add KeePassXC
- Add Novel MT + Light Novel World
- Add Nebulo
- Change section Domain Names to Domain Privacy + add 1.1.1.1: Faster & Safer Internet
- Add Unstoppable Domains
- Add Fopnu
- Remove rarbg
- Update The Proxy Bay
- Add section VNC
- Add link to WireGuard + OpenVPN
- Change Windows 10 Privacy to Windows 11 Privacy
- Add Panda Novel
- Add Champagne
- Add Anime Scrap + Animity
- Add ReadNovelFull
- Add Miru
- Add Piracy Index
- Add MirrorAce
- Add Bergamot Translator
- Add RARBG Backup
- Add QuickNovel
- Add Av1an
- Add qrcp
- Add Szyszka + BleachBit + Czkawka
- Add JPEG XL bash converter
- Add Enable Right Click & Copy
- Add Piracy megathread
- Add Youtube NonStop
- Add SponsorBlock
- Add SearX
- Add Firejail
- Add Nebulo
- Add Shadowsocks
- Add FREEMEDIAHECKYEAH
- Add Piracy BG

### CODE REVIEW

**Comment by Shakil-Shahadat** [comment]
Thanks for the changes. Please allow me a little time to go through all the changes.

In the future, please send a PR for each change, that way it'll be easier to review and merge each change.

**Comment by Shakil-Shahadat** [comment]
Please STOP. Most of the commits you are adding have nothing to do with piracy. You didn't listen to my request to make individual PR either. STOP adding any more commit to these and strictly restrict to piracy-related links.

**Comment by KonoromiHimaries** [comment]
ok

**Comment by abcasada** [comment]
@Shakil-Shahadat, I recommend closing this PR without merging due to being stale, having no actual URLs, and previous comments that the suggested items aren't related to piracy.

**Pull request closed without merging**
